# Asurajang 설정 파일
#
# 증강 표시 정보   → augment/description.yml
# 증강 수치 설정   → augment/config.yml
# 기지 모드 설정   → nexus.yml

death-gold-penalty:
  enabled: true     # 사망 시 골드 감소 여부
  ratio: 0.10       # 감소 비율 (현재 보유 골드 기준)
