package me.qmftm.asurajang.augmentation;

import me.qmftm.asurajang.augmentation.effect.AugmentationEffect;
import me.qmftm.asurajang.augmentation.effect.BoogieWoogieEffect;
import me.qmftm.asurajang.augmentation.effect.UnBreakableEffect;
import me.qmftm.asurajang.augmentation.effect.UnRuinEffect;
import me.qmftm.asurajang.augmentation.effect.SaturatedFatEffect;
import me.qmftm.asurajang.augmentation.effect.GamblerEffect;
import me.qmftm.asurajang.augmentation.effect.DivineLoveEffect;
import me.qmftm.asurajang.augmentation.effect.WindBurstEffect;
import me.qmftm.asurajang.augmentation.effect.StrongStrongEffect;
import me.qmftm.asurajang.augmentation.effect.StrongWeakEffect;
import me.qmftm.asurajang.augmentation.effect.HentaiEffect;
import me.qmftm.asurajang.augmentation.effect.DeadfulEffect;
import me.qmftm.asurajang.augmentation.effect.MolaMolaEffect;
import me.qmftm.asurajang.augmentation.effect.CleanUpEffect;
import me.qmftm.asurajang.augmentation.effect.GlassCannonEffect;
import me.qmftm.asurajang.augmentation.effect.GuiltPleasureEffect;
import me.qmftm.asurajang.augmentation.effect.DivergentFistEffect;
import me.qmftm.asurajang.augmentation.effect.HeavyForceEffect;
import me.qmftm.asurajang.augmentation.effect.BlackFlashEffect;
import me.qmftm.asurajang.augmentation.effect.FeatherFallingEffect;
import me.qmftm.asurajang.augmentation.effect.CopyEffect;
import me.qmftm.asurajang.augmentation.effect.ColdBloodEffect;
import me.qmftm.asurajang.augmentation.effect.DivineDogsEffect;
import me.qmftm.asurajang.augmentation.effect.SelfBomberEffect;
import me.qmftm.asurajang.augmentation.effect.DropkickEffect;
import me.qmftm.asurajang.augmentation.effect.ExecutionerSwordEffect;
import me.qmftm.asurajang.augmentation.effect.StatPlusPlusPlusEffect;
import me.qmftm.asurajang.augmentation.effect.TabDancerEffect;
import me.qmftm.asurajang.augmentation.effect.SniperDuelEffect;
import me.qmftm.asurajang.augmentation.effect.GrabEffect;
import me.qmftm.asurajang.augmentation.effect.BodyBombEffect;
import me.qmftm.asurajang.augmentation.effect.CharmEffect;
import me.qmftm.asurajang.augmentation.effect.InfiniteGoldEffect;
import me.qmftm.asurajang.augmentation.effect.TotalConcentrationEffect;
import me.qmftm.asurajang.augmentation.effect.AegisEffect;
import me.qmftm.asurajang.augmentation.effect.SealEffect;
import me.qmftm.asurajang.augmentation.effect.MassIsPowerEffect;
import me.qmftm.asurajang.augmentation.effect.StatEffect;
import me.qmftm.asurajang.augmentation.effect.QuickDrawEffect;
import me.qmftm.asurajang.augmentation.effect.FleeEffect;
import me.qmftm.asurajang.augmentation.effect.AssassinEffect;
import me.qmftm.asurajang.augmentation.effect.DragonScaleEffect;
import me.qmftm.asurajang.augmentation.effect.RepulsionEffect;
import me.qmftm.asurajang.augmentation.effect.InevitableExistenceEffect;
import me.qmftm.asurajang.augmentation.effect.ExtraHealthEffect;
import me.qmftm.asurajang.augmentation.effect.NanoTechnologyEffect;
import me.qmftm.asurajang.augmentation.effect.VampireEffect;
import me.qmftm.asurajang.augmentation.effect.ResilientSpiritEffect;
import me.qmftm.asurajang.augmentation.effect.SpiritBombEffect;
import me.qmftm.asurajang.augmentation.effect.BonusEffect;
import me.qmftm.asurajang.augmentation.effect.MutualDestructionEffect;
import me.qmftm.asurajang.augmentation.effect.BodyguardEffect;
import me.qmftm.asurajang.augmentation.effect.BlinkEffect;
import me.qmftm.asurajang.augmentation.effect.SacredFlameEffect;
import me.qmftm.asurajang.augmentation.effect.WaitingEffect;
import me.qmftm.asurajang.augmentation.effect.CorrosionEffect;
import me.qmftm.asurajang.augmentation.effect.DragonEffect;
import me.qmftm.asurajang.augmentation.effect.DragonSlayerEffect;
import me.qmftm.asurajang.augmentation.effect.BlackHoleEffect;
import me.qmftm.asurajang.augmentation.effect.ManeuverGearEffect;
import me.qmftm.asurajang.augmentation.effect.ShadowLordEffect;
import me.qmftm.asurajang.augmentation.effect.PursuerEffect;
import me.qmftm.asurajang.augmentation.effect.HuntingInstinctEffect;
import me.qmftm.asurajang.augmentation.effect.TimeTravelerEffect;
import me.qmftm.asurajang.augmentation.effect.TimeLordEffect;
import me.qmftm.asurajang.augmentation.effect.FiercePursuerEffect;
import me.qmftm.asurajang.augmentation.effect.VengefulGhostEffect;
import me.qmftm.asurajang.augmentation.effect.RabiesEffect;
import me.qmftm.asurajang.augmentation.effect.YouAreAlreadyDeadEffect;
import org.jetbrains.annotations.Nullable;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

public class AugmentationRegistry {

    private static final Map<String, Supplier<AugmentationEffect>> REGISTRY = new HashMap<>();

    static {
        REGISTRY.put("BlackFlash",    BlackFlashEffect::new);
        REGISTRY.put("Deadful",       DeadfulEffect::new);
        REGISTRY.put("BoogieWoogie",  BoogieWoogieEffect::new);
        REGISTRY.put("MolaMola",      MolaMolaEffect::new);
        REGISTRY.put("Hentai",        HentaiEffect::new);
        REGISTRY.put("Copy",          CopyEffect::new);
        REGISTRY.put("SniperDuel",    SniperDuelEffect::new);
        REGISTRY.put("DivergentFist", DivergentFistEffect::new);
        REGISTRY.put("ColdBlood",     ColdBloodEffect::new);
        REGISTRY.put("HeavyForce",    HeavyForceEffect::new);
        REGISTRY.put("SelfBomber",    SelfBomberEffect::new);
        REGISTRY.put("GuiltPleasure", GuiltPleasureEffect::new);
        REGISTRY.put("GlassCannon",   GlassCannonEffect::new);
        REGISTRY.put("CleanUp",       CleanUpEffect::new);
        REGISTRY.put("FeatherFalling",FeatherFallingEffect::new);
        REGISTRY.put("DivineDogs",    DivineDogsEffect::new);
        REGISTRY.put("StrongWeak",    StrongWeakEffect::new);
        REGISTRY.put("StrongStrong",  StrongStrongEffect::new);
        REGISTRY.put("WindBurst",     WindBurstEffect::new);
        REGISTRY.put("DivineLove",    DivineLoveEffect::new);
        REGISTRY.put("UnBreakable",   UnBreakableEffect::new);
        REGISTRY.put("UnRuin",        UnRuinEffect::new);
        REGISTRY.put("SaturatedFat",  SaturatedFatEffect::new);
        REGISTRY.put("Gambler",       GamblerEffect::new);
        REGISTRY.put("Dropkick",          DropkickEffect::new);
        REGISTRY.put("ExecutionerSword",  ExecutionerSwordEffect::new);
        REGISTRY.put("StatPlusPlusPlus",  StatPlusPlusPlusEffect::new);
        REGISTRY.put("TabDancer",         TabDancerEffect::new);
        REGISTRY.put("Grab",              GrabEffect::new);
        REGISTRY.put("BodyBomb",          BodyBombEffect::new);
        REGISTRY.put("Charm",             CharmEffect::new);
        REGISTRY.put("InfiniteGold",      InfiniteGoldEffect::new);
        REGISTRY.put("TotalConcentration", TotalConcentrationEffect::new);
        REGISTRY.put("Aegis",             AegisEffect::new);
        REGISTRY.put("Seal",              SealEffect::new);
        REGISTRY.put("MassIsPower",       MassIsPowerEffect::new);
        REGISTRY.put("Stat",              StatEffect::new);
        REGISTRY.put("QuickDraw",         QuickDrawEffect::new);
        REGISTRY.put("Flee",              FleeEffect::new);
        REGISTRY.put("Assassin",          AssassinEffect::new);
        REGISTRY.put("DragonScale",       DragonScaleEffect::new);
        REGISTRY.put("Repulsion",         RepulsionEffect::new);
        REGISTRY.put("InevitableExistence", InevitableExistenceEffect::new);
        REGISTRY.put("ExtraHealth",       ExtraHealthEffect::new);
        REGISTRY.put("NanoTechnology",    NanoTechnologyEffect::new);
        REGISTRY.put("Vampire",           VampireEffect::new);
        REGISTRY.put("ResilientSpirit",   ResilientSpiritEffect::new);
        REGISTRY.put("SpiritBomb",        SpiritBombEffect::new);
        REGISTRY.put("Bonus",             BonusEffect::new);
        REGISTRY.put("MutualDestruction", MutualDestructionEffect::new);
        REGISTRY.put("Bodyguard",         BodyguardEffect::new);
        REGISTRY.put("Blink",             BlinkEffect::new);
        REGISTRY.put("SacredFlame",       SacredFlameEffect::new);
        REGISTRY.put("Waiting",           WaitingEffect::new);
        REGISTRY.put("Corrosion",         CorrosionEffect::new);
        REGISTRY.put("Dragon",            DragonEffect::new);
        REGISTRY.put("DragonSlayer",      DragonSlayerEffect::new);
        REGISTRY.put("BlackHole",         BlackHoleEffect::new);
        REGISTRY.put("ManeuverGear",      ManeuverGearEffect::new);
        REGISTRY.put("ShadowLord",        ShadowLordEffect::new);
        REGISTRY.put("Pursuer",           PursuerEffect::new);
        REGISTRY.put("HuntingInstinct",   HuntingInstinctEffect::new);
        REGISTRY.put("TimeTraveler",      TimeTravelerEffect::new);
        REGISTRY.put("TimeLord",          TimeLordEffect::new);
        // 시너지 효과
        REGISTRY.put("FiercePursuer",       FiercePursuerEffect::new);
        REGISTRY.put("VengefulGhost",       VengefulGhostEffect::new);
        REGISTRY.put("Rabies",              RabiesEffect::new);
        REGISTRY.put("YouAreAlreadyDead",   YouAreAlreadyDeadEffect::new);
    }

    @Nullable
    public static AugmentationEffect create(String id) {
        Supplier<AugmentationEffect> factory = REGISTRY.get(id);
        return factory != null ? factory.get() : null;
    }
}
